import { assets } from '../assets/assets'


export const data = [
    {
        id: 1,
        name: 'Arijit Singh',
        genre: 'Bollywood',
        location: 'Mumbai',
        language: 'Hindi',
        image: 'https://i.pinimg.com/736x/e8/d0/9d/e8d09dc7491d9801c8edb409a40186c7.jpg',
        rating: 4.8,
        description: 'A versatile Bollywood playback singer with a soulful voice.',
        pricePerEvent: 5000,
        slots: [ '01-03-2025'
        ],
        profilePic: true,
    },
    {
        id: 2,
        name: 'Shreya Ghoshal',
        genre: 'Bollywood',
        location: 'Kolkata',
        language: 'Hindi',
        image: 'https://today.ganganews.com/wp-content/uploads/2023/11/Shreya-Ghoshal.jpg',
        rating: 4.9,
        description: 'One of the leading playback singers in Indian cinema.',
        pricePerEvent: 6000,
        profilePic: true,
    },
    {
        id: 3,
        name: 'Sunidhi Chauhan',
        genre: 'Bollywood',
        location: 'Delhi',
        language: 'Hindi',
        image: 'https://blackhattalent.com/wp-content/uploads/2023/07/1601537507_screenshot_20201001-130025_instagram_copy_1200x800.jpg',
        rating: 4.7,
        description: 'Known for her energetic and versatile singing style.',
        pricePerEvent: 5500,
        profilePic: true,
    },
    {
        id: 4,
        name: 'Anirudh Ravichander',
        genre: 'Indian Pop',
        location: 'Chennai',
        language: 'Tamil',
        image: 'https://static.toiimg.com/thumb/msid-92872439,width-1200,height-900,resizemode-4/.jpg',
        rating: 4.6,
        description: 'A popular music composer and singer in the Tamil film industry.',
        pricePerEvent: 4800,
        profilePic: true,
    },
    {
        id: 5,
        name: 'Neeti Mohan',
        genre: 'Bollywood',
        location: 'Mumbai',
        language: 'Hindi',
        image: 'https://i.zoomtventertainment.com/media/Neeti_Mohan.jpg',
        rating: 4.5,
        description: 'A contemporary Bollywood singer with a melodious voice.',
        pricePerEvent: 4500,
        profilePic: true,
    },
    {
        id: 6,
        name: 'Armaan Malik',
        genre: 'Indian Pop',
        location: 'Mumbai',
        language: 'Hindi',
        image: 'https://pbs.twimg.com/media/F4rsKjVbMAAIs2g.jpg',
        rating: 4.4,
        description: 'A young and popular singer known for his romantic ballads.',
        pricePerEvent: 4200,
        profilePic: true,
    },
    {
        id: 7,
        name: 'Lata Mangeshkar',
        genre: 'Bollywood',
        location: 'Mumbai',
        language: 'Hindi',
        image: 'https://m.media-amazon.com/images/M/MV5BMjQ3OTc3NTA4Ml5BMl5BanBnXkEAL._V1_.jpg',
        rating: 5.0,
        description: 'The Nightingale of India, legendary playback singer.',
        pricePerEvent: 7000,
        profilePic: true,
    },
    {
        id: 8,
        name: 'Kishore Kumar',
        genre: 'Bollywood',
        location: 'Mumbai',
        language: 'Hindi',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Kishore_Kumar.jpg/440px-Kishore_Kumar.jpg',
        rating: 4.9,
        description: 'Versatile singer, actor, and composer of Bollywood fame.',
        pricePerEvent: 6500,
        profilePic: true,
    },
    {
        id: 9,
        name: 'Asha Bhosle',
        genre: 'Bollywood',
        location: 'Mumbai',
        language: 'Hindi',
        image: 'https://pbs.twimg.com/profile_images/1697921049039474688/mK1t7_aH_400x400.jpg',
        rating: 4.8,
        description: 'Another iconic voice in Bollywood, known for her range.',
        pricePerEvent: 6200,
        profilePic: true,
    },
    {
        id: 10,
        name: 'Udit Narayan',
        genre: 'Bollywood',
        location: 'Mumbai',
        language: 'Hindi',
        image: 'https://static.toiimg.com/thumb/msid-88577725,width-400,resizemode-4/88577725.jpg',
        rating: 4.7,
        description: 'A prominent Bollywood playback singer known for his romantic songs.',
        pricePerEvent: 5800,
        profilePic: true,
    },
];